name: PushBuild

on:
  push:
    branches:
      - master
env:
  FLUTTER_VERSION: '3.29.2'
  APP_NAME: 'formaldehyde_detection_admin'

jobs:
  job_apk:
    name: 构建android软件
    runs-on: ubuntu-latest
    env:
      version: "pushAction"
      ALIAS: ${{ secrets.ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: 修改版本号
        run: |
          sed -i "s/version: .*/version: 1.0.0+1/" pubspec.yaml
      - name: 编译环境设置 Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: 构建签名环境
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: echo $SIGNING_KEY | base64 -d > android/app/key.jks
      - name: 设置flutter编译环境
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION  }}
          cache: true
          cache-key: flutter-${{ runner.os }}-${{ env.FLUTTER_VERSION }}
          cache-path: ${{ runner.tool_cache }}/flutter
      - name: 执行编译命令分架构
        run: |
          flutter pub get
          flutter build apk --release --target-platform=android-arm,android-arm64 --split-per-abi
      - name: 重命名文件
        run: |
          mv build/app/outputs/apk/release/app-armeabi-v7a-release.apk build/app/outputs/apk/release/schedule-android-armeabi-v7a-${{ env.version }}.apk
          mv build/app/outputs/apk/release/app-arm64-v8a-release.apk build/app/outputs/apk/release/schedule-android-arm64-v8a-${{ env.version }}.apk
      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: android-split
          path: build/app/outputs/apk/release/schedule-android-*-${{ env.version }}.apk
      - name: 执行编译命令全架构
        run: |
          flutter pub get
          flutter build apk --release --target-platform=android-arm,android-arm64
      - name: 重命名文件
        run: mv build/app/outputs/apk/release/app-release.apk build/app/outputs/apk/release/schedule-android-all-${{ env.version }}.apk
      - name: 上传产物全架构
        uses: actions/upload-artifact@v4
        with:
          name: android-all
          path: build/app/outputs/apk/release/schedule-android-all-${{ env.version }}.apk

  job_ipa:
    name: 构建ios软件
    runs-on: macos-latest
    env:
      version: "pushAction"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: 修改版本号
        run: |
          sed -i "" "s/version: .*/version: 1.0.0+1/" pubspec.yaml
      - name: 编译环境设置
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION  }}
          cache: true
          cache-key: flutter-${{ runner.os }}-${{ env.FLUTTER_VERSION }}
          cache-path: ${{ runner.tool_cache }}/flutter
      - name: Build (ios)
        run: |
          flutter pub get
          flutter build ipa --release --no-codesign
          cd build/ios/archive/Runner.xcarchive/Products/Applications
          mkdir -p Payload
          mv Runner.app Payload
          zip -9 release-ios.ipa -r Payload
      - name: 重命名文件
        run:  mv build/ios/archive/Runner.xcarchive/Products/Applications/release-ios.ipa build/ios/archive/Runner.xcarchive/Products/Applications/schedule-ios-${{ env.version }}.ipa
      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: ios
          path: build/ios/archive/Runner.xcarchive/Products/Applications/schedule-ios-${{ env.version }}.ipa